disabled_rules: # rule identifiers to exclude from running
  - vertical_whitespace
  - trailing_whitespace
  - trailing_comma
  - type_name
  - nesting
  - identifier_name
  - function_parameter_count


opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
  - closure_spacing
  - yoda_condition

included: # paths to include during linting. `--path` is ignored if present.
  - StoreSearch

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - StoreSearch/R.generated.swift

  - UnitTests
  - UITests
  - Frameworks

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

force_cast: warning # implicitly. Give warning only for force casting

cyclomatic_complexity: 25

line_length: 160

